name: librino
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get_it: ^7.2.0
  flutter_bloc: ^8.1.2
  intl: ^0.18.1
  lottie: ^2.2.0
  equatable: ^2.0.5
  firebase_core: ^2.7.0
  firebase_storage: ^11.2.2
  cloud_firestore: ^4.4.3
  shimmer: ^2.0.0
  reorderables: ^0.6.0
  video_player: ^2.5.3
  fluttertoast: ^8.2.1
  json_annotation: ^4.8.0
  just_audio: ^0.9.31
  flutter_html: ^2.1.2
  share_plus: ^6.3.4
  firebase_auth: ^4.6.0
  hydrated_bloc: ^9.1.1
  google_fonts: ^4.0.4
  path_provider: ^2.0.15
  uuid: ^3.0.7
  toggle_switch: ^2.1.0
  dotted_border: ^2.0.0+1
  image_picker: ^0.8.7+5
  flutter_ffmpeg: ^0.4.2
  camera: ^0.10.5+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  json_serializable: ^6.6.1
  build_runner: ^2.3.3
  flutter_launcher_icons: ^0.11.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/animations/
    - assets/sounds/

dependency_overrides:
  path_provider: ^2.0.0